blank_issues_enabled: false
contact_links:
  - name: ğŸŒ FileSentinel Official Website
    url: https://wangchujiang.com/file-sentinel/
    about: Introduction to the FileSentinel app on the official website!